### ISSUE TITLE
How-to question on using mime-parser

### ISSUE THREAD

**Issue by barrydegraaff** [emailjs/emailjs-mime-parser#12]
@felixhammerl and others

I am trying to use emailjs-mime-parser, but I think I am missing some knowledge to implement the steps in the README.

Could you help me to use mime-parser in a simple html page, so I can integrate this library into Zimbra OpenPGP Zimlet. Thanks!!

What I am doing can be found here (and is attached to issue):

https://github.com/Zimbra-Community/pgp-zimlet/blob/stable/test/mimeparser/mimeparser-test.html#L286

Its an simple html page with a textarea that countains a raw email message, doing the steps from the readme and then:

      parser.write(new TextEncoder("utf-8").encode(document.getElementById('input').value));
      //mimeparser.js:75 Uncaught TypeError: Cannot read property 'fromTypedArray' of undefinedMimeParser.write
      
      parser.write(document.getElementById('input').value);
      //Uncaught TypeError: Cannot read property 'parseHeaderValue' of undefined
      parser.end();

Both cases throw an error and as such, I cannot get the resulting email object. (example attached) What am I missing here?

[mimeparser.zip](https://github.com/emailjs/emailjs-mime-parser/files/281813/mimeparser.zip)

**Comment by andris9** [comment]
You use global instances to load the dependencies but in this case loading order matters, so you should include mimefuncs.js before mailparser.js

this should work:

```html
<script src="mimeparser.js"></script>
<script src="addressparser.js"></script>
<script src="mimefuncs.js"></script>
<script src="mimeparser.js"></script>
<script src="stringencoding.js"></script>
```

**Comment by barrydegraaff** [comment]
That works, thanks!

I was reading your blogpost:
https://blog.whiteout.io/2014/07/01/emailjs-the-hard-thing-about-old-things/

And I know how you must have felt. Unfortunately I think most people take this stuff for granted, but you made a great effort- thanks!!
