### ISSUE TITLE
Cannot get attachment filename from Content-Disposition header

### ISSUE THREAD

**Issue by barrydegraaff** [emailjs/emailjs-mime-parser#14]
It seems, this library does not parse attachment filenames from the Content-Disposition header.

I have this in the source of the email:
Content-Type: application/pdf
Content-Disposition: attachment; filename="testfile.pdf"
Content-Transfer-Encoding: base64

In most use cases, this:
node.contentType.params.name
Would get me the attachment filename, however there is no node.contentDisposition.params.name dumping the entire node to the console.log, it looks like this part may be missing from the implementation.

On the other hand, maybe I overlooked something. Regards Barry

**Comment by barrydegraaff** [comment]
Alternatively we can get the filename from node.headers['content-disposition'][0].params.filename... maybe this is what is what I am intended to do?

**Comment by barrydegraaff** [comment]
closed without comment? Does that mean that the supposed way is using: node.headers['content-disposition'][0].params.filename...

**Comment by felixhammerl** [comment]
sorry, i assumed this was outdated by now. yes, that's how i used it...

**Comment by barrydegraaff** [comment]
thanks!

**Comment by felixhammerl** [comment]
I an abandoned pet project of mine, i used this: https://github.com/felixhammerl/up/blob/master/app/src/render/account/inbox.js#L216-L402

**Comment by barrydegraaff** [comment]
Nice, I will copy-paste if needed!
