### ISSUE TITLE
How do I use this parser exactly?

### ISSUE THREAD

**Issue by NetOperatorWibby** [emailjs/emailjs-mime-parser#15]
Forgive me if this sounds like a dumb question, but I'm new to emailjs. Here is my code:

```
client.listMessages("INBOX", "1:10", ["uid", "flags", "envelope", "bodystructure", "body[]"]).then((messages) => {
  messages.forEach((message) => {
    console.log(message["body[]"]);
    console.log("------");
  });
});
```

I can see the content of my email, but I don't know how to parse the result. I'm going to output the messages in HTML, but there's a lot of stuff in there that doesn't need to be viewable, like `MIME-Version`s and such. I'm confused as to how I would integrate this into my code.

**Comment by andris9** [comment]
body.peek[] gives you the raw rfc822 source of the message. See the [README](https://github.com/emailjs/emailjs-mime-parser/blob/master/README.md) of this project for documentation of how to parse such raw message

**Comment by NetOperatorWibby** [comment]
I must be doing something wrong then because this doesn't work:

```
const parser = require("emailjs-mime-parser");

client.connect().then(() => {
  client.listMessages("INBOX", "1:*", ["uid", "flags", "envelope", "bodystructure", "body.peek[]"]).then((messages) => {
    messages.forEach((message) => {
      console.log('Flags for ' + message.uid + ': ' + message.flags.join(', '));
      console.log("------");

      parser.write(message["body.peek[]"]);
      parser.end();

      parser.onbody = (node, chunk) => {
        console.log("Should get something...");
        console.log("Received %s bytes for %s", chunk.byteLength, node.path.join("."));
      };
    });
  });
});
```

**Comment by andris9** [comment]
I think you need to first set up the `onbody` and then call `write` and `end`

**Comment by NetOperatorWibby** [comment]
How do I do that? I don't understand how to by following the README.

**Comment by andris9** [comment]
Replace the order in your own code, move write and end lines after onbody definition

**Comment by NetOperatorWibby** [comment]
I'm still not getting anything. `parser.onbody` doesn't get called.

**Comment by TomasHubelbauer** [comment]
I'm also struggling with this, especially because when using `body.peek[]` seems to fail with my message returned from Fastmail.

**Comment by felixhammerl** [comment]
@TomasHubelbauer there has been a major rework and this thread is no longer even remotely accurate. Please see the README for more information:

```import parse from 'emailjs-mime-parse'
parse(String) -> MimeNode```
