### ISSUE TITLE
Mail parsing fails when there is corrupted body content

### ISSUE THREAD

**Issue by arwyn** [emailjs/emailjs-mime-parser#17]
Due to https://github.com/emailjs/emailjs-base64/issues/1 I have emails that are completely unparseble. 

While in my case the bug is in the decoder, it is also possible for the email content itself to be corrupted in some way. If this happens I would expect the un-corrupted MimeNode(s) to be to be usable.

Could you please improve your parser error handling to be more resistant to broken data. No need for magic recovery or anything, just being able to get access to the non-broken tree nodes is enough.

Thank you

**Comment by felixhammerl** [comment]
Fixed and published as v2.0.1

**Comment by nifgraup** [comment]
dd67310 causes https://github.com/emailjs/emailjs-mime-parser/issues/35
