### ISSUE TITLE
How to use "charset=binary" by default?

### ISSUE THREAD

**Issue by YuryStrozhevsky** [emailjs/emailjs-mime-parser#23]
I am trying to decode this message:
```
Content-Type: application/pkcs7-mime; name=smime.p7m; smime-type=enveloped-data
Content-Description: Enveloped Data
Content-Disposition: attachment; filename=smime.p7m
Content-Transfer-Encoding: base64
From: sender@example.com
To: recipient@example.com
Subject: Example S/MIME encrypted message
Date: Sun, 25 Feb 2018 09:28:14 +0000
Message-Id: <1519550894482-b208bdc8-7f8e90aa-4af6b4fa@example.com>
MIME-Version: 1.0

MIIB3AYJKoZIhvcNAQcDoIIBzTCCAckCAQIxggFuMIIBagIBADAjMB4xHDAJBgNVBAYTAlJVMA8G
A1UEAx4IAFQAZQBzAHQCAQEwPAYJKoZIhvcNAQEHMC+gDzANBglghkgBZQMEAgMFAKEcMBoGCSqG
SIb3DQEBCDANBglghkgBZQMEAgMFAASCAQBDyepahKyM+hceeF7J+pyiSVYLElKyFKff9flMs1VX
ZaBQRcEYpIqw9agD4u+aHlIOJ6AtdCbxaV0M8q6gjM4E5lUFUOqG/QIycdG2asZ0lza/DL8SdxfA
3WE9Ij5IEqFbtnykbfORK+5XWT0nYs/OMN0NKeCwXjElNsezX9IAIgxHgwcVYW+szXpRlarjriAC
TDG/M+Xl5YtyAhmHWFncBSfWM8e2q+AKh3eCal1lH4eXtGICc4rad4f6845YJwXL8DYYS+GdLVAY
EXKuHr0N7g4aHTs9B8EQqHmYdaHWTi3h0ZPkvAE+wwfm9xjvL2z2HrfpYyMTvALrefvSt7sGMIAG
CSqGSIb3DQEHATAdBglghkgBZQMEAQIEEKt6VqFcNz/VYFwu85DTOqGggAQgIHc45LBiYIQqhxNw
hlRk4BxMiyiQRdLcVdCwwkKyX2sAAAAA
```
So, when I am trying to use `parser.content.buffer` as an input for further operations I get incorrect result. As I found it is all because your parser does not consider to use `charset=binary` by default and apply `utf-8` decoding to the binary text. 

The question is: would it be possible to set any options for your package in order to get all the correct binary data I want? Or it would require a code fix?

**Comment by felixhammerl** [comment]
Fixed.

`Content-Type: application/pkcs7-mime; name=smime.p7m; smime-type=enveloped-data; charset=binary` works in the latest version.

See the test: https://github.com/emailjs/emailjs-mime-parser/blob/master/src/mimeparser-unit.js#L254-L280

**Comment by YuryStrozhevsky** [comment]
Would it be possible to omit char set setting and have binary by default?

**Comment by felixhammerl** [comment]
the more i take a look at this, i guess the more binary makes sense ...

**Comment by felixhammerl** [comment]
closing in favor of #18
