### ISSUE TITLE
Unable to use "emailjs-mime-parser" since no "dist" directory included

### ISSUE THREAD

**Issue by YuryStrozhevsky** [emailjs/emailjs-mime-parser#25]
As you stated in `package.json`:
```
  ...
  "main": "dist/mimeparser",
  "name": "emailjs-mime-parser",
  ...
```
But unfortunately the `dist` directory is not included in NPM package. Please append, for example, `prepublishOnly` script into your `package.json` file.

**Comment by YuryStrozhevsky** [comment]
As an addition I can say that seems such problem exist only for `emailjs-mime-parser@2.0.2` and `emailjs-mime-parser@2.0.3`. In `emailjs-mime-parser@2.0.1` the `dist` directory exists.

**Comment by felixhammerl** [comment]
oh crap, you're right ... i had scripted that process for the very reason of making it more resilient. so sorry about that! will fix that right away
