### ISSUE TITLE
Denial of Service Vulnerability - No limit on empty attachments

### ISSUE THREAD

**Issue by jorangreef** [emailjs/emailjs-mime-parser#39]
emailjs-mime-parser should validate the number of empty attachments it is willing to parse, to avoid a DOS vulnerability, see:

https://snyk.io/vuln/npm:emailjs-mime-parser:20180625

https://snyk.io/blog/how-to-crash-an-email-server-with-a-single-email

**Comment by felixhammerl** [comment]
Thanks for filing the bug.

I agree that this is not a nice thing to happen in the toolchain. The issue you are outlining is currently unsolved, as it would require an entire rewrite of the entire parsing library, which is currently out of scope for the time I can spend on this library.

A possible solution would be to rewrite this entire library to a streaming approach, as it was originally intended. The nested nature of MIME makes this a non-trivial issue. I welcome community contributions on this issue.

**Comment by jorangreef** [comment]
Thanks @felixhammerl 

Alternatively, could your top-level mime object not keep a count of the total number of parts parsed, and throw an exception when this exceeds 1000?

**Comment by felixhammerl** [comment]
That does sound like an interesting quick fix... Will have a look at it as soon as I have some bandwidth. Will use the email example from the snyk blog as test input.

**Comment by felixhammerl** [comment]
Fixed in 2.0.7
