### ISSUE TITLE
Converting TypedArrays to text

### ISSUE THREAD

**Issue by devconcept** [emailjs/emailjs-mime-parser#46]
This library converts `text/plain` data to `Uint8Array` by default.

Why not preserve the `_bodyBuffer` content on the [`_emitBody`](https://github.com/emailjs/emailjs-mime-parser/blob/da78f7336b1fe7ca3934c38f86ebf803dc50e50b/src/node.js#L324) call instead of [discarding it](https://github.com/emailjs/emailjs-mime-parser/blob/da78f7336b1fe7ca3934c38f86ebf803dc50e50b/src/node.js#L326) so we don't have to convert it back to text for representation?

 If there is a reason for this behavior you should consider an option to specify how to get the results of the parser.

**Comment by devconcept** [comment]
Also when using the `str2arr` some characters are corrupted when decoding. Why not use the [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) class to convert text to binary? Using your own functions causes `TextDecoder` not to work as expected.

**Comment by felixhammerl** [comment]
The character corruption issue has been fixed in 2.0.6.

**Comment by felixhammerl** [comment]
The API of the library was written so that it returns typed arrays no matter what the node was. Also, any text is converted to UTF-8, regardless of the input. Therefore, i don't quite see the benefit for this approach, as it's just one call to the TextEncoder...

**Comment by devconcept** [comment]
Well one of the problem this library has is that, for example, it converts base64 string into a typed array, then it converts them into a regular string and then again into a typed array. This unnecessary conversion is the reason why sometimes you get corrupt data when using this library.
